[package]
name = "wannacryaboutit_2ic80"
version = "0.1.0"
edition = "2024"

[dependencies]
age = "0.11.1"
anyhow = "1.0.100"
zeroize = "1.8.2"
chacha20poly1305 = "0.10.1"
rand = "0.9.2"
rand_core = "0.9.3"
